@echo off
md zh_cn\News
md zh_cn\Updates
md zh_cn\Maintenance
md zh_cn\Events
md zh_cn\Important
md zh_tw\News
md zh_tw\Updates
md zh_tw\Maintenance
md zh_tw\Events
md zh_tw\Important
md en_us\News
md en_us\Updates
md en_us\Maintenance
md en_us\Events
md en_us\Important
md en_eu\News
md en_eu\Updates
md en_eu\Maintenance
md en_eu\Events
md en_eu\Important
md ja_jp\News
md ja_jp\Updates
md ja_jp\Maintenance
md ja_jp\Events
md ja_jp\Important
pause *.*